# Generated by Django 4.1.3 on 2023-02-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0002_lahan_namegreenhouse'),
        ('notifikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='lahan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lahannotif', to='lahan.lahan'),
        ),
    ]
