# Generated by Django 4.1.3 on 2023-02-16 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0012_alter_lahan_imggreenhouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifikasi', '0002_notifikasi_lahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='lahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_lahan', to='lahan.lahan'),
        ),
    ]
