# Generated by Django 4.1.3 on 2023-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0003_notifikasi_user_alter_notifikasi_lahan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifikasi',
            old_name='text_notifikasi',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='lahan',
        ),
    ]
