# Generated by Django 4.1.3 on 2023-02-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifikasi', '0007_remove_notifikasi_user_notifikasi_lahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='lahan',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
