# Generated by Django 4.1.3 on 2023-02-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0012_alter_lahan_imggreenhouse'),
        ('notifikasi', '0008_remove_notifikasi_lahan_notifikasi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='user',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='lahan',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='notif_lahan', to='lahan.lahan'),
            preserve_default=False,
        ),
    ]
