# Generated by Django 4.1.3 on 2023-02-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='nameGreenhouse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
