# Generated by Django 4.1.3 on 2023-02-10 04:22

from django.db import migrations, models
import lahan.models


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0003_lahan_longitude_lahan_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='imgGreenhouse',
            field=models.ImageField(blank=True, null=True, upload_to=lahan.models.upload_to),
        ),
    ]
