# Generated by Django 4.1.3 on 2023-02-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0004_lahan_imggreenhouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lahan',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='user',
        ),
    ]
