# Generated by Django 4.1.3 on 2023-02-12 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lahan', '0006_rename_longitude_lahan_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lahan', to=settings.AUTH_USER_MODEL),
        ),
    ]
