# Generated by Django 4.1.3 on 2023-02-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lahan', '0010_alter_lahan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='jml_bibit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
