# Generated by Django 4.1.3 on 2023-02-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_udara', models.CharField(blank=True, max_length=255)),
                ('suhu_tanah', models.CharField(blank=True, max_length=255)),
                ('ph', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
