# Generated by Django 4.1.3 on 2023-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatur', '0002_temperatur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatur',
            name='cahaya',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='temperatur',
            name='kelembapan_tanah',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='temperatur',
            name='kelembapan_udara',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
