# Generated by Django 4.1.3 on 2023-03-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktuator', '0002_aktuator_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuator',
            name='created_at',
        ),
    ]
