# Generated by Django 4.1.3 on 2023-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktuator', '0003_remove_aktuator_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=123),
            preserve_default=False,
        ),
    ]
